# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Sync Test
short_description: Random number generation challenge for each submission
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Cras egestas a libero nec sagittis.
evaluation_script: evaluation_script.zip
remote_evaluation: false
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: true
tags:
- random-number-generation
- machine-learning
- data-science
- computer-vision
leaderboard:
- id: 1
  schema:
    default_order_by: Total
    labels:
    - Metric1
    - Metric2
    - Metric3
    - Total
    metadata:
      Metric1:
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        sort_ascending: true
      Metric2:
        description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        sort_ascending: true
challenge_phases:
- allowed_email_ids: []
  allowed_submission_file_types: .json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz
  challenge: 1
  codename: dev
  default_submission_meta_attributes:
  - is_visible: true
    name: method_name
  - is_visible: true
    name: method_description
  - is_visible: true
    name: project_url
  - is_visible: true
    name: publication_url
  description: templates/challenge_phase_1_description.html
  disable_logs: false
  end_date: 2099-04-25 23:59:59
  id: 1
  is_active: true
  is_partial_submission_evaluation_enabled: false
  is_public: true
  is_restricted_to_select_one_submission: false
  is_submission_public: true
  leaderboard_public: false
  max_concurrent_submissions_allowed: 3
  max_submissions: 50
  max_submissions_per_day: 5
  max_submissions_per_month: 50
  name: Dev Phase
  start_date: 2019-01-19 00:00:00
  submission_meta_attributes:
  - description: Sample
    name: TextAttribute
    required: false
    type: text
  - description: Sample
    name: SingleOptionAttribute
    options:
    - A
    - B
    - C
    type: radio
  - description: Sample
    name: MultipleChoiceAttribute
    options:
    - alpha
    - beta
    - gamma
    type: checkbox
  - description: Sample
    name: TrueFalseField
    required: true
    type: boolean
  test_annotation_file: annotations/test_annotations_devsplit.json
- allowed_email_ids: []
  challenge: 2
  codename: test
  default_submission_meta_attributes:
  - is_visible: true
    name: method_name
  - is_visible: true
    name: method_description
  - is_visible: true
    name: project_url
  - is_visible: true
    name: publication_url
  description: templates/challenge_phase_2_description.html
  disable_logs: false
  end_date: 2099-05-24 23:59:59
  id: 2
  is_active: true
  is_partial_submission_evaluation_enabled: false
  is_public: true
  is_restricted_to_select_one_submission: false
  is_submission_public: true
  leaderboard_public: true
  max_concurrent_submissions_allowed: 3
  max_submissions: 50
  max_submissions_per_day: 5
  max_submissions_per_month: 50
  name: Test Phase
  start_date: 2019-01-01 00:00:00
  submission_meta_attributes:
  - description: Sample
    name: TextAttribute
    type: text
  - description: Sample
    name: SingleOptionAttribute
    options:
    - A
    - B
    - C
    type: radio
  - description: Sample
    name: MultipleChoiceAttribute
    options:
    - alpha
    - beta
    - gamma
    type: checkbox
  - description: Sample
    name: TrueFalseField
    type: boolean
  test_annotation_file: annotations/test_annotations_testsplit.json
dataset_splits:
- codename: train_split
  id: 1
  name: Train Split
- codename: test_split
  id: 2
  name: Test Split
challenge_phase_splits:
- challenge_phase_id: 1
  dataset_split_id: 1
  is_leaderboard_order_descending: true
  leaderboard_decimal_precision: 2
  leaderboard_id: 1
  show_execution_time: true
  show_leaderboard_by_latest_submission: true
  visibility: 1
- challenge_phase_id: 2
  dataset_split_id: 1
  is_leaderboard_order_descending: true
  leaderboard_decimal_precision: 2
  leaderboard_id: 1
  show_leaderboard_by_latest_submission: false
  showeceution_time: false
  visibility: 3
- challenge_phase_id: 2
  dataset_split_id: 2
  is_leaderboard_order_descending: true
  leaderboard_decimal_precision: 2
  leaderboard_id: 1
  show_execution_time: true
  show_leaderboard_by_latest_submission: true
  visibility: 1
